import { type ChildProcess, spawn, spawnSync } from "node:child_process";
import { stat } from "node:fs/promises";
import { createInterface } from "node:readline";
import { ERROR_MESSAGE_MAX_BYTES, STDERR_TAIL_BYTES } from "../constants.js";
import { BatonError } from "../errors.js";
import type { Logger } from "../observability/logger.js";
import { now } from "../util.js";
import type { AgentEventCallback, AgentSession, TurnResult } from "./runner.js";

const isWindows = process.platform === "win32";

interface ResolvedWindowsCommand {
  executable: string;
  prefixArgs: string[];
  viaCmdShim: boolean;
}

/**
 * `cmd.exe` expands `%VAR%` even inside quoted arguments before a `.cmd`/`.bat`
 * wrapper receives them. Doubling `%` preserves the literal character so the
 * wrapper passes the original argv through to the real CLI.
 */
export function escapeWindowsCmdArg(arg: string): string {
  return arg.replace(/%/g, "%%");
}

/**
 * On Windows, resolve an argv-form executable so that .cmd/.bat shims
 * (generated by npm global installs) are routed through cmd.exe while real
 * executables are returned for direct spawn. Returns [executable, prefixArgs].
 *
 * For .exe / .com (or anything already resolved): [path, []]
 * For .cmd / .bat shims: ["cmd.exe", ["/d", "/s", "/c", fullPath]]
 *
 */
function resolveWindowsCommand(executable: string): ResolvedWindowsCommand {
  if (/\.(exe|com)$/i.test(executable)) {
    return { executable, prefixArgs: [], viaCmdShim: false };
  }

  const result = spawnSync("where.exe", [executable], { encoding: "utf8" });
  const stdout = result.stdout ?? "";
  if (result.status !== 0 || !stdout.trim()) {
    return { executable, prefixArgs: [], viaCmdShim: false };
  }

  const fullPath = stdout.trim().split("\n")[0]?.trim() ?? executable;
  if (/\.(cmd|bat)$/i.test(fullPath)) {
    return {
      executable: "cmd.exe",
      prefixArgs: ["/d", "/s", "/c", fullPath],
      viaCmdShim: true,
    };
  }
  return { executable: fullPath, prefixArgs: [], viaCmdShim: false };
}

/** Kill the agent's whole process group.
 *  Unix: kills the process group (requires spawn with detached: true).
 *  Windows: uses taskkill /F /T to kill the full process tree. */
export function killProcessTree(proc: ChildProcess): void {
  if (proc.pid !== undefined) {
    if (isWindows) {
      spawnSync("taskkill", ["/F", "/T", "/PID", String(proc.pid)]);
      return;
    }
    try {
      process.kill(-proc.pid, "SIGKILL");
      return;
    } catch {
      // Fall through to single-process kill.
    }
  }
  proc.kill("SIGKILL");
}

/** SPEC §9.5 Invariant 1: validate the workspace cwd before launching an agent. */
export async function ensureWorkspaceDir(workspace: string): Promise<void> {
  let isDir = false;
  try {
    isDir = (await stat(workspace)).isDirectory();
  } catch {
    isDir = false;
  }
  if (!isDir) {
    throw new BatonError(
      "invalid_workspace_cwd",
      `not a directory: ${workspace}`,
    );
  }
}

/** Terminate a session's process tree if it is still running. */
export function stopSessionProcess(session: AgentSession): void {
  if (session.proc && session.proc.exitCode === null && !session.proc.killed) {
    killProcessTree(session.proc);
  }
  session.proc = null;
}

export interface RunSubprocessOptions {
  /** Shell command string (spawned via bash -lc) or argv array (spawned directly). */
  command: string | string[];
  /** Per-turn timeout; on expiry the whole process tree is killed (SPEC §10.3). */
  timeoutMs: number;
  /** When set, written to the child's stdin then closed; otherwise stdin is ignored. */
  stdin?: string;
  onEvent: AgentEventCallback;
  /** Parse one stdout line; return a TurnResult once the turn outcome is known. */
  onLine: (line: string) => TurnResult | null;
  /** Optional logger for subprocess lifecycle events (debug level). */
  logger?: Logger;
}

/**
 * Run one agent process, stream stdout lines through `onLine`, enforce the
 * turn timeout, and normalize the exit into a TurnResult. Shared by the
 * Claude Code and Copilot adapters (SPEC §10.1, §10.2); only command
 * construction and line parsing differ.
 *
 * When `command` is a string it is executed via `bash -lc` (backward-
 * compatible shell path). When it is a string[] the executable is spawned
 * directly with no shell wrapper (Windows-native path).
 *
 * The spawned process is stored on `session.proc` so stopSession can terminate
 * it, and cleared once the process closes.
 */
export function runSubprocess(
  session: AgentSession,
  opts: RunSubprocessOptions,
): Promise<TurnResult> {
  return new Promise((resolvePromise) => {
    const useStdin = opts.stdin !== undefined;
    // detached: own process group on Unix so killProcessTree can kill the
    // whole agent subtree via -pid. On Windows taskkill handles tree kill, so
    // detached is not needed.
    // Resolve the executable + args so the spawn ternary below can use literal
    // stdio tuples, which lets TypeScript infer non-null stdout/stderr types.
    let executable: string;
    let execArgs: string[];
    if (typeof opts.command === "string") {
      // Shell path: bash parses the command string (backward-compatible).
      executable = "bash";
      execArgs = ["-lc", opts.command];
    } else {
      // Argv path: spawn directly on Unix; on Windows resolve .cmd/.bat shims
      // via where.exe so that only script wrappers go through cmd.exe while
      // real executables are spawned directly with literal argv (SPEC §10.1).
      const [first, ...rest] = opts.command;
      // Command is validated non-empty by validateDispatchConfig before dispatch.
      if (!first) {
        resolvePromise({ ok: false, error: "startup_failed: empty command" });
        return;
      }
      if (isWindows) {
        const resolved = resolveWindowsCommand(first);
        executable = resolved.executable;
        execArgs = [
          ...resolved.prefixArgs,
          ...(resolved.viaCmdShim ? rest.map(escapeWindowsCmdArg) : rest),
        ];
      } else {
        executable = first;
        execArgs = rest;
      }
    }
    const proc = useStdin
      ? spawn(executable, execArgs, {
          cwd: session.workspace,
          stdio: ["pipe", "pipe", "pipe"],
          detached: !isWindows,
        })
      : spawn(executable, execArgs, {
          cwd: session.workspace,
          stdio: ["ignore", "pipe", "pipe"],
          detached: !isWindows,
        });
    session.proc = proc;

    opts.logger?.debug("subprocess spawned", {
      pid: proc.pid,
      ...(typeof opts.command === "string"
        ? { command: opts.command }
        : { executable }),
      workspace: session.workspace,
    });

    if (useStdin && proc.stdin) {
      proc.stdin.on("error", () => {
        // Process may exit before consuming stdin; close handler reports it.
      });
      proc.stdin.write(opts.stdin);
      proc.stdin.end();
    }

    let stderrTail = "";
    proc.stderr.on("data", (chunk: Buffer) => {
      stderrTail = (stderrTail + chunk.toString("utf8")).slice(
        -STDERR_TAIL_BYTES,
      );
    });

    let result: TurnResult | null = null;
    let timedOut = false;
    // Guard against Node.js firing both `error` and `close` on spawn failure
    // (ENOENT etc.). The first handler to resolve wins; the second must not
    // call onEvent again (callbacks are not idempotent).
    let resolved = false;
    const timer = setTimeout(() => {
      timedOut = true;
      killProcessTree(proc);
    }, opts.timeoutMs);

    const rl = createInterface({ input: proc.stdout });
    rl.on("line", (line) => {
      const r = opts.onLine(line);
      if (r) result = r;
    });

    proc.on("error", (err) => {
      clearTimeout(timer);
      if (resolved) return;
      resolved = true;
      session.proc = null;
      opts.logger?.debug("subprocess error", {
        pid: proc.pid,
        error: String(err),
      });
      resolvePromise({ ok: false, error: `startup_failed: ${String(err)}` });
    });
    proc.on("close", (code) => {
      clearTimeout(timer);
      if (resolved) return;
      resolved = true;
      session.proc = null;
      opts.logger?.debug("subprocess closed", {
        pid: proc.pid,
        exit_code: code,
        timed_out: timedOut,
        ...(stderrTail.length > 0
          ? { stderr_tail: stderrTail.slice(-200) }
          : {}),
      });
      if (timedOut) {
        opts.onEvent({
          event: "turn_cancelled",
          timestamp: now(),
          message: "turn_timeout",
        });
        resolvePromise({ ok: false, error: "turn_timeout" });
      } else if (result) {
        resolvePromise(result);
      } else {
        const error = `process_exit code=${code} stderr=${stderrTail.slice(-ERROR_MESSAGE_MAX_BYTES)}`;
        opts.onEvent({
          event: "turn_failed",
          timestamp: now(),
          message: error,
        });
        resolvePromise(code === 0 ? { ok: true } : { ok: false, error });
      }
    });
  });
}
